/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package studyactivityapp;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author abdul.nafey18
 */
public class StudyActivityGUI extends javax.swing.JFrame {

    /**
     * Creates new form StudyActivityGUI
     */
//declare variables
//initialising the array list
    private int time,duration;
    private String day,module,topic,teammates,assessmentname;
    private ArrayList<StudyActivity> StudyActivities;
    StudyActivity SA = new StudyActivity();
    PersonalSession PS = new PersonalSession();
    GroupProjectSession GPS = new GroupProjectSession();
//creating the array list  
    public StudyActivityGUI() {
        initComponents();
        StudyActivities = new ArrayList<>();
        loadData();
        topicTextField.setVisible(false);
        topicLabel.setVisible(false);
        teammatesTextField.setVisible(false);
        teammatesLabel.setVisible(false);
        AssessmentTextField.setVisible(false);
        AssessmentLabel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        MainTitle = new javax.swing.JLabel();
        DayLabel = new javax.swing.JLabel();
        DayTextField = new javax.swing.JTextField();
        ModuleLabel = new javax.swing.JLabel();
        ModuleTextField = new javax.swing.JTextField();
        TimeLabel = new javax.swing.JLabel();
        TimeTextField = new javax.swing.JTextField();
        DurationLabel = new javax.swing.JLabel();
        DurationTextField = new javax.swing.JTextField();
        topicLabel = new javax.swing.JLabel();
        topicTextField = new javax.swing.JTextField();
        teammatesLabel = new javax.swing.JLabel();
        teammatesTextField = new javax.swing.JTextField();
        AssessmentLabel = new javax.swing.JLabel();
        AssessmentTextField = new javax.swing.JTextField();
        AddButton = new javax.swing.JButton();
        ViewButton = new javax.swing.JButton();
        SaveButton = new javax.swing.JButton();
        PSRadioButton = new javax.swing.JRadioButton();
        GPSRadioButton = new javax.swing.JRadioButton();
        DeleteButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainTitle.setFont(new java.awt.Font("Baskerville", 3, 24)); // NOI18N
        MainTitle.setText("Study Activity Log");

        DayLabel.setFont(new java.awt.Font("Bodoni 72", 1, 24)); // NOI18N
        DayLabel.setText("Day:");

        DayTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DayTextFieldActionPerformed(evt);
            }
        });

        ModuleLabel.setFont(new java.awt.Font("Bodoni 72", 1, 24)); // NOI18N
        ModuleLabel.setText("Module Name:");

        TimeLabel.setFont(new java.awt.Font("Bodoni 72", 1, 24)); // NOI18N
        TimeLabel.setText("Time:");

        DurationLabel.setFont(new java.awt.Font("Bodoni 72", 1, 24)); // NOI18N
        DurationLabel.setText("Duration in Mins:");

        topicLabel.setFont(new java.awt.Font("Bodoni 72", 1, 24)); // NOI18N
        topicLabel.setText("Study Topic:");

        teammatesLabel.setFont(new java.awt.Font("Bodoni 72", 1, 24)); // NOI18N
        teammatesLabel.setText("Team Mates:");

        AssessmentLabel.setFont(new java.awt.Font("Bodoni 72", 1, 24)); // NOI18N
        AssessmentLabel.setText("Assessment Name:");

        AddButton.setFont(new java.awt.Font("Baskerville", 3, 18)); // NOI18N
        AddButton.setText("Add");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });

        ViewButton.setFont(new java.awt.Font("Baskerville", 3, 18)); // NOI18N
        ViewButton.setText("View");
        ViewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewButtonActionPerformed(evt);
            }
        });

        SaveButton.setFont(new java.awt.Font("Baskerville", 3, 18)); // NOI18N
        SaveButton.setText("Save");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(PSRadioButton);
        PSRadioButton.setText("Personal Session");
        PSRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PSRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(GPSRadioButton);
        GPSRadioButton.setText("Group Project Session");
        GPSRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GPSRadioButtonActionPerformed(evt);
            }
        });

        DeleteButton.setFont(new java.awt.Font("Baskerville", 3, 12)); // NOI18N
        DeleteButton.setText("Delete Last Activity");
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(GPSRadioButton)
                    .addComponent(topicLabel)
                    .addComponent(ModuleLabel)
                    .addComponent(DayLabel)
                    .addComponent(DurationLabel)
                    .addComponent(TimeLabel)
                    .addComponent(AssessmentLabel)
                    .addComponent(teammatesLabel)
                    .addComponent(PSRadioButton))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(AddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(DeleteButton)
                                .addGap(18, 18, 18)
                                .addComponent(ViewButton, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(DayTextField)
                            .addComponent(ModuleTextField)
                            .addComponent(topicTextField)
                            .addComponent(DurationTextField)
                            .addComponent(TimeTextField)
                            .addComponent(teammatesTextField)
                            .addComponent(AssessmentTextField))
                        .addGap(54, 54, 54))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(MainTitle)
                                .addGap(185, 185, 185))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(SaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(292, 292, 292))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(MainTitle)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(DayLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DayTextField))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ModuleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ModuleTextField))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TimeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TimeTextField))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(DurationLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DurationTextField))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(topicLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(topicTextField))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(teammatesLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(teammatesTextField))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AssessmentLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AssessmentTextField))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ViewButton, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                            .addComponent(AddButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DeleteButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(PSRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaveButton)
                    .addComponent(GPSRadioButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DayTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DayTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DayTextFieldActionPerformed
//provides a text field to the user upon selecting the radio button
    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        // TODO add your handling code here:
        if (PSRadioButton.isSelected()) {
            PS.setDay(DayTextField.getText());
            PS.setModule(ModuleTextField.getText());
            PS.setTime(Integer.parseInt(TimeTextField.getText()));
            PS.setDuration(Integer.parseInt(DurationTextField.getText()));
            PS.setTopic(topicTextField.getText());
            StudyActivities.add(PS);

        } else if (GPSRadioButton.isSelected()) {
            GPS.setDay(DayTextField.getText());
            GPS.setModule(ModuleTextField.getText());
            GPS.setTime(Integer.parseInt(TimeTextField.getText()));
            GPS.setDuration(Integer.parseInt(DurationTextField.getText()));
            GPS.setTeammates(teammatesTextField.getText());
            GPS.setAssessmentname(AssessmentTextField.getText());
            StudyActivities.add(GPS);
    }//GEN-LAST:event_AddButtonActionPerformed
}
//prints the entered data in the text field and displays it to the user
    private void ViewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewButtonActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < StudyActivities.size(); i++) {
            StudyActivity PS = StudyActivities.get(i);
            JOptionPane.showMessageDialog(null, PS.getDetails());
        }
    }//GEN-LAST:event_ViewButtonActionPerformed
//Personal Session radio button which selected hides other labels and text fields of group project session
    private void PSRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PSRadioButtonActionPerformed
        // TODO add your handling code here:
        topicTextField.setVisible(true);
        topicLabel.setVisible(true);
        teammatesTextField.setVisible(false);
        teammatesLabel.setVisible(false);
        AssessmentTextField.setVisible(false);
        AssessmentLabel.setVisible(false);
    }//GEN-LAST:event_PSRadioButtonActionPerformed
//Group Project Session radio button which selected hides other labels and text fields of personal session
    private void GPSRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GPSRadioButtonActionPerformed
        // TODO add your handling code here:
        topicTextField.setVisible(false);
        topicLabel.setVisible(false);
        teammatesTextField.setVisible(true);
        teammatesLabel.setVisible(true);
        AssessmentTextField.setVisible(true);
        AssessmentLabel.setVisible(true);
    }//GEN-LAST:event_GPSRadioButtonActionPerformed
//Saves the entered data into activitylog.dat file
    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        // TODO add your handling code here:
        File outFile;
        FileOutputStream fStream;
        ObjectOutputStream oStream;

        try{
            outFile = new File("activitylog.dat");
            fStream = new FileOutputStream(outFile);
            oStream = new ObjectOutputStream(fStream);

            oStream.writeObject(StudyActivities);
            JOptionPane.showMessageDialog(null,"Activity saved");
        } catch (IOException e) {
            System.out.println("Error saving activity"+e);
        }
    }//GEN-LAST:event_SaveButtonActionPerformed
//Loads activitylog.dat file automatically upon starting the GUI application and displays the stored logs in the file    
    public final void loadData(){
        File inFile;
        FileInputStream fStream;
        ObjectInputStream oStream;

        try{
            inFile = new File("activitylog.dat");
            fStream = new FileInputStream(inFile);
            oStream = new ObjectInputStream(fStream);

            StudyActivities = (ArrayList<StudyActivity>) oStream.readObject();
            for(StudyActivity PS:StudyActivities){   
                JOptionPane.showMessageDialog(null, PS.getDetails());   
            }
            oStream.close();
            
        } 
        catch(IOException e){
            System.out.println("Error saving book"+e);
        }
        catch(ClassNotFoundException ex){
            System.out.println(ex);
        }
    }
//Deletes the last activity added
    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        // TODO add your handling code here:
        if (StudyActivities.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Sorry, there are no Study Activity logs to delete");
        } 
        else {
            StudyActivities.remove(StudyActivities.size()-1);                   
        }
    }//GEN-LAST:event_DeleteButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudyActivityGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudyActivityGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudyActivityGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudyActivityGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudyActivityGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JLabel AssessmentLabel;
    private javax.swing.JTextField AssessmentTextField;
    private javax.swing.JLabel DayLabel;
    private javax.swing.JTextField DayTextField;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JLabel DurationLabel;
    private javax.swing.JTextField DurationTextField;
    private javax.swing.JRadioButton GPSRadioButton;
    private javax.swing.JLabel MainTitle;
    private javax.swing.JLabel ModuleLabel;
    private javax.swing.JTextField ModuleTextField;
    private javax.swing.JRadioButton PSRadioButton;
    private javax.swing.JButton SaveButton;
    private javax.swing.JLabel TimeLabel;
    private javax.swing.JTextField TimeTextField;
    private javax.swing.JButton ViewButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel teammatesLabel;
    private javax.swing.JTextField teammatesTextField;
    private javax.swing.JLabel topicLabel;
    private javax.swing.JTextField topicTextField;
    // End of variables declaration//GEN-END:variables
}
